spring.application.name=artifacts

#Secret Manager
spring.config.import=sm@:
spring.cloud.gcp.secretmanager.allow-default-secret=true
artifacts.api-key=${sm@artifacts-api-key}

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY:placeholder}
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY:placeholder}
